### ISSUE TITLE
MSI and Gigabyte BIOS PPT setting and reducing idle power usage

### ISSUE THREAD

**Issue by eadmaster** [nickbabcock/sff.life#382]
![_MSI B450-A PRO mobo BIOS Advanced CPU Configuration SnapShot](https://user-images.githubusercontent.com/925171/78766113-22d3ae80-7989-11ea-88c2-1d02e90bfa98.png)
(from my MSI B450-A PRO mobo)

A picture from a Gigabite motherboard is [here (it's in the AMD CBS submenu)](https://i.imgur.com/VdB8xJw.jpg).

This worked quite well in reducing the *max* power consumption of my Ryzen 3200G.

However the *idle* power consumption is still quite higher than my previous Pentium Kaby Lake CPU.
Any tips for reducing that as well?
I've tried undervolting but it didn't help much.

**Comment by nickbabcock** [comment]
Thanks for the screenshot, what name / handle would you like credited?

And yeah, I can look at my measurements again but I don't think idle power usage changed too drastically for me either. Lowering idle power is an interesting topic as always on HTPCs or home servers could definitely benefit from lower power usage.

**Comment by eadmaster** [comment]
> Thanks for the screenshot, what name / handle would you like credited?

`eadmaster` is fine.
Btw the Gigabyte mobo shot is from [this reddit post](https://old.reddit.com/r/Amd/comments/ceakbs/if_you_want_to_save_powerreduce_thermals_reduce/#eu4hnh2).

> Lowering idle power is an interesting topic as always on HTPCs or home servers could definitely benefit from lower power usage.

I had the best results by tweaking the Windows Power Saver plan and reducing the max allowed frequency + [ParkControl](https://bitsum.com/parkcontrol/) to enable core parking.

I've also read that the Ryzens have a different power consumption curve when transitioning from idle to load [due to the Infinity Fabric](https://www.anandtech.com/show/13124/the-amd-threadripper-2990wx-and-2950x-review/4), so i am going to do measurements again on the Pentium at low load.

**Comment by nickbabcock** [comment]
Thanks for the info! I've incorporated the screenshots into the post.
