### ISSUE TITLE
another PPT BIOS shot from my Asrock Deskmini A300

### ISSUE THREAD

**Issue by eadmaster** [nickbabcock/sff.life#535]
this is different from the [one shown here](https://sff.life/how-to-undervolt-ryzen-cpu/#gatsby-chunk-mapping):
![P1070855_crop](https://user-images.githubusercontent.com/925171/82731192-613ce700-9d05-11ea-908e-ab50afaf0957.JPG)

I've asked the asrock support team for infos on the "0" values that should mean default.

**Comment by nickbabcock** [comment]
Updated, thanks!
