### ISSUE TITLE
Duplicate spreadsheet

### ISSUE THREAD

**Issue by MasonLyons** [nickbabcock/sff.life#678]
The 2 spreadsheets [here](https://sff.life/how-to-undervolt-gpu/) at the end seem to be the same when the second should be one showing extra undervolting

**Comment by nickbabcock** [comment]
Oops, good catch. When I migrated the site I forgot to fix the image reference. This has been fixed by

f64aa04e1c2c3da9ebef2823a7e0c78350c246fa

If this is not fixed, let me know
